### ISSUE TITLE
Allow specifying timestamps for metrics

### ISSUE THREAD

**Issue by j2ghz** [MindFlavor/prometheus_exporter_base#17]
The prometheus format specification has an optional timestamp after the value, but it's not possible to specify it with `PrometheusMetric`'s `render_sample` currently. I was going to open a PR adding an `Option<>` parameter for it, but that'd be a breaking change. Is that fine, or should I make it as another function (e.g. `render_sample_timestamp`)?
```
metric_name [
  "{" label_name "=" `"` label_value `"` { "," label_name "=" `"` label_value `"` } [ "," ] "}"
] value [ timestamp ]
```
> The timestamp is an int64 (milliseconds since epoch, i.e. 1970-01-01 00:00:00 UTC, excluding leap seconds), represented as required by Go's ParseInt() function.
>https://prometheus.io/docs/instrumenting/exposition_formats/#text-format-details

**Comment by MindFlavor** [comment]
I think a single function is better even if it will mean introducing a breaking change: the API should be as similar as possible to the specification (within reason OC)!
