### ISSUE TITLE
More ergonimic PrometheusMetric generation

### ISSUE THREAD

**Issue by pard68** [MindFlavor/prometheus_exporter_base#19]
Wanted to reach out and see what you thought about making the PrometheusMetric more ergonomic, using a builder model. I'm thinking something along the lines of how you setup argparsing in claps:
```
let metrics = PrometheusExporterBuilder::new()
    .metric(
        .name("foo")
        .help("a metric for foo")
        .type("gauge")
        .label("bar", 1)
        .label("baz", "buzz")
    )
    .build();

metrics::render()
```

I am more than willing to make the patch for this, I just wanted to run it by you before I started.

**Comment by MindFlavor** [comment]
I think it's an excellent idea!

**Comment by MindFlavor** [comment]
I took a stab at your suggestion in the above PR. What do you think? You can see it in action in the `Simple` example.

**Comment by pard68** [comment]
I like that, didn't even think of adding the `build` method on the PrometheusMetric.

**Comment by MindFlavor** [comment]
I had time to work on this further. 

Here is what I've reached so far:

```rust
        let pc = PrometheusMetric::build()
            .with_name("folder_size")
            .with_metric_type(MetricType::Counter)
            .with_help("Size of the folder")
            .build();

        // this could be condensed in a single line if needed
        pc
            .create_instance()
            .with_label("folder", "/var/log")
            .with_value(total_size_log)
            .render_with_header()
```

It's similar to what you had in mind but you cannot chain different instances. You still have to call `render_header()` separately if you want to achieve this. It's more error prone but also does not force the `PrometheusMetric` to store all the data until the `build()` command. 

I'll give it some more though, in the meantime please tell me what you think!

**Comment by pard68** [comment]
Sorry I was totally going to look at this more and then something else came up and since my exporter was working I couldn't find a good excuse to get back to this...

This is definitely going the right way I think! Even with just the first bit you had done I think makes your project easily the most ergonomic and usable of the Rust openmetric/prometheus metric exporter libraries.

If I find time soon I'll poke at this as well.

**Comment by MindFlavor** [comment]
I think I have achieved something very similar to what you proposed:

```rust
PrometheusMetric::build()
    .with_name("folder_size")
    .with_metric_type(MetricType::Counter)
    .with_help("Size of the folder")
    .build()    
    .render_and_append_instance(
        &PrometheusInstance::new()
            .with_label("folder", "/var/log") 
            .with_value(total_size_log)
            .with_current_timestamp()
            .expect("error getting the current UNIX epoch"),
    )
    .render_and_append_instance(
        &PrometheusInstance::new()
            .with_label("folder", "/tmp")
            .with_value(total_size_tmp),
    )
    .render()
```

We can't still chain multiple metrics but I think this strikes a good balance between fluency and having to store information. I'll finalize some things (like docs and version) and merge it!
