### ISSUE TITLE
Basic auth feature

### ISSUE THREAD

**Issue by AnySk** [MindFlavor/prometheus_exporter_base#27]
Is it possible to add basic auth feature as [prometheus docs](https://prometheus.io/docs/prometheus/latest/configuration/https/) describes. So [prometheus_wireguard_exporter](https://github.com/MindFlavor/prometheus_wireguard_exporter), for example, could extend envs to use it

**Comment by MindFlavor** [comment]
Good point, it's worth investigating! :+1:
