### ISSUE TITLE
Rename 'PrometheusCounter' to 'PrometheusMetric'

### ISSUE THREAD

**Issue by soloradish** [MindFlavor/prometheus_exporter_base#4]
In Prometheus's API spec, Counter is one type of metrics.

**Comment by MindFlavor** [comment]
Yes you are right! I will definitely rename it ASAP. Thanks!

**Comment by soloradish** [comment]
And, the function name   'render_sample'  is better than 'render_counter' in my opinion. also 'labels' better than 'attributes'

**Comment by MindFlavor** [comment]
Excellent, thank you! 
Do you mind checking the [PR](https://github.com/MindFlavor/prometheus_exporter_base/pull/7) if it seems right by you? I've tried to follow your suggestions to the letter!
