### ISSUE TITLE
Write a proper README

### ISSUE THREAD

**Issue by MindFlavor** [MindFlavor/prometheus_exporter_base#6]
I **hate** projects without a README. 
And I do it all the time :cry: , like in this repo. Shame on me :see_no_evil: !!

**Comment by Folyd** [comment]
What the different between this project and [rust-prometheus](https://github.com/pingcap/rust-prometheus)?
BTW, please add a README and documentation, thanks!

**Comment by MindFlavor** [comment]
Hi Folyd, I should definitely write a proper README... In the meantime you can refer to this blog post: [https://dev.to/mindflavor/let-s-build-a-prometheus-exporter-in-rust-30pd](https://dev.to/mindflavor/let-s-build-a-prometheus-exporter-in-rust-30pd). It's a bit outdated but the essence is the same.

As for the goal of this crate, I was writing many exporters in rust, both for open source (such as [prometheus_iota_exporter](https://github.com/MindFlavor/prometheus_iota_exporter) and [prometheus_wireguard_exporter](https://github.com/MindFlavor/prometheus_wireguard_exporter)) and closed source projects, and I was sick of copypasting the same boilerplate (init hyper, check for valid verbs, etc..). So I decided to write a crate to handle most of these boring tasks. Its goal is to allow writing a proper prometheus exporter in few lines as possible. 

*I hope it makes sense* :blush:
